spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-04.cleardb.com/heroku_b9f023322d6382c
    username: b2c45309f14a05
    password: 1ee45b2c
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

#mysql://b2c45309f14a05:1ee45b2c@us-cdbr-east-04.cleardb.com/heroku_b9f023322d6382c?reconnect=true