spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://us-cdbr-east-04.cleardb.com/heroku_b9f023322d6382c}
    username: ${JDBC_DATABASE_USERNAME:b2c45309f14a05}
    password: ${JDBC_DATABASE_PASSWORD:a8c9718f7c3a70a}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect