spring:
  datasource:    url: jdbc:mysql://localhost:3306/Grupo-21-BDD-OO2-2021
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNaming.Strategy
      properties:
        dialect: org.hibernate.dialect.MySQL5Dialect