INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (1, "1846", "ADROGUE");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (2, "1846", "ALMIRANTE BROWN");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (3, "1856", "BARRIO ALMAFUERTE (GLEW-PDO. ALMTE. BROWN)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (4, "1852", "BARRIO ARZENO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (5, "1847", "BARRIO ASUNCION");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (6, "1852", "BARRIO DOÑA SOL");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (7, "1854", "BARRIO DON LUIS");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (8, "1852", "BARRIO EL GAUCHO (BURZACO-PDO. ALMIRANTE BROWN)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (9, "1852", "BARRIO EL HORNERO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (10, "1849", "BARRIO EL PATRONATO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (11, "1849", "BARRIO EL TREBOL");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (12, "1854", "BARRIO GENERAL BELGRANO (LONGCHAMPS-PDO. ALMIRANTE BROWN)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (13, "1856", "BARRIO GORRITI");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (14, "1847", "BARRIO GUADALUPE (RAFAEL CALZADA-PDO. ALMIRANTE BROWN)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (15, "1852", "BARRIO LA CARLOTA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (16, "1852", "BARRIO LA CUMBRE (BURZACO-PDO. ALMIRANTE BROWN)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (17, "1847", "BARRIO LA GLORIA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (18, "1849", "BARRIO LA JOVITA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (19, "1856", "BARRIO LA REFORMA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (20, "1846", "BARRIO LA TABLADA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (21, "1849", "BARRIO LAS MALVINAS");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (22, "1849", "BARRIO LAS TUNAS");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (23, "1846", "BARRIO LOMA VERDE");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (24, "1854", "BARRIO LOS ALAMOS");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (25, "1856", "BARRIO PARQUE IPONA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (26, "1849", "BARRIO PARQUE MARIANO MORENO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (27, "1856", "BARRIO PARQUE ROMA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (28, "1854", "BARRIO RAYO DE SOL (LONGCHAMPS-PDO. ALMIRANTE BROWN)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (29, "1852", "BARRIO SAKURA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (30, "1847", "BARRIO SAN JAVIER");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (31, "1846", "BARRIO SAN JUAN (ALMIRANTE BROWN-PDO. ALMIRANTE BROWN)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (32, "1849", "BARRIO SAN LUCAS");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (33, "1847", "BARRIO SAN PEDRO (RAFAEL CALZADA-PDO. ALMIRANTE BROWN)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (34, "1849", "BARRIO SANTA CLARA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (35, "1849", "BARRIO SANZ");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (36, "1847", "BARRIO VILLA LAURA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (37, "1847", "BARRIO ZABALA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (38, "1852", "BURZACO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (39, "1849", "CLAYPOLE");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (40, "1856", "GLEW");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (41, "1846", "JOSE MARMOL");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (42, "1854", "LONGCHAMPS");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (43, "1852", "MINISTRO RIVADAVIA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (44, "1847", "RAFAEL CALZADA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (45, "1847", "VILLA CALZADA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (46, "1847", "VILLA LAURA (RAFAEL CALZADA-PDO. ALMTE. BROWN)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (47, "1856", "VILLA PARIS");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (48, "1870", "AVELLANEDA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (49, "1874", "BARRIO OBRERO VILLA AVELLANEDA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (50, "1870", "BULLRICH");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (51, "1872", "COSTA DE SARANDI");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (52, "1874", "COSTA DE VILLA DOMINICO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (53, "1870", "CRUCECITA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (54, "1871", "DOCK SUD");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (55, "1870", "GERLI (PARTIDO AVELLANEDA)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (56, "1871", "ISLA MACIEL");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (57, "1870", "KILOMETRO 5 (ESTACION FCGR)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (58, "1872", "LA COSTA (SARANDI-PDO. AVELLANEDA)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (59, "1870", "LA MOSCA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (60, "1874", "LAS QUINTAS (VILLA DOMINICO-PDO. AVELLANEDA)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (61, "1870", "PIÑEYRO (PDO. AVELLANEDA)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (62, "1872", "SARANDI");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (63, "1874", "VILLA BARILARI");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (64, "1870", "VILLA CASTELLINO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (65, "1874", "VILLA CORINA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (66, "1874", "VILLA DOMINICO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (67, "1875", "VILLA GONNET");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (68, "1874", "VILLA HUE");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (69, "1874", "VILLA ITE");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (70, "1870", "VILLA MERCADO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (71, "1870", "VILLA MODELO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (72, "1874", "VILLA NUÑEZ");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (73, "1870", "VILLA POBLADORA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (74, "1870", "VILLA PORVENIR");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (75, "1875", "WILDE");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (76, "1875", "WILDE ESTE");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (77, "1825", "A. A. FERNANDEZ");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (78, "1822", "BARRIO MARIANO MORENO (VALENTIN ALSINAPDO. LANUS)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (79, "1825", "BARRIO VEINTISEIS DE ABRIL");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (80, "1826", "BARRIO VILLA GENERAL BALCARCE");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (81, "1825", "BARRIO VILLA OFELIA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (82, "1822", "CARAZA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (83, "1824", "GERLI (PARTIDO LANUS)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (84, "1824", "LANUS");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (85, "1826", "LAS COLONIAS");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (86, "1825", "MONTE CHINGOLO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (87, "1826", "REMEDIOS DE ESCALADA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (88, "1822", "VALENTIN ALSINA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (89, "1826", "VILLA CABRAL");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (90, "1822", "VILLA CARAZA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (91, "1826", "VILLA EDEN ARGENTINO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (92, "1822", "VILLA ILASA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (93, "1824", "VILLA INDUSTRIALES");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (94, "1822", "VILLA JARDIN");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (95, "1826", "VILLA POMPEO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (96, "1828", "BANFIELD");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (97, "1836", "BARRIO ALTO VERDE (LLAVALLOL-PDO. LOMAS DE ZAMORA)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (98, "1836", "BARRIO LOS PINOS (LLAVALLOL-PDO. LOMAS DE ZAMORA)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (99, "1828", "BARRIO MARIANO MORENO (BANFIELD-PDO. LOMAS DE ZAMORA)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (100, "1832", "BARRIO PARQUE BARON");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (101, "1828", "BARRIO PARQUE UNION Y FRATERNIDAD");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (102, "1828", "BARRIO PROVINCIAS UNIDAS");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (103, "1834", "BARRIO SAN CRISTOBAL");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (104, "1834", "BARRIO SAN FERNANDO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (105, "1835", "BARRIO SAN JOSE (PDO. LOMAS DE ZAMORA)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (106, "1834", "BARRIO SAN JUAN (TEMPERLEY-PDO. LOMAS DE ZAMORA)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (107, "1836", "BARRIO SANTA CATALINA (LLAVALLOL-PDO. LOMAS DE ZAMORA)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (108, "1834", "BARRIO VILLA LA PAZ");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (109, "1828", "BARRIO VILLA MAIPU");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (110, "1834", "CABAÑA SPINDOLA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (111, "1831", "FIORITO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (112, "1832", "KILOMETRO 34 (APEADERO FCDFS) (SANTA MARTA-PDO. LOMAS DE ZAMORA)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (113, "1836", "LLAVALLOL");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (114, "1832", "LOMAS DE ZAMORA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (115, "1834", "PARADA PASCO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (116, "1832", "PARQUE MITRE");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (117, "1834", "PASCO (APEADERO FCGB)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (118, "1836", "SANTA CATALINA (ESTACION FCDFS) (LLAVALLOL-PDO. LOMAS DE ZAMORA)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (119, "1834", "TEMPERLEY");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (120, "1834", "TURDERA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (121, "1829", "VILLA ALBERTINA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (122, "1832", "VILLA BARRIO ARCA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (123, "1832", "VILLA BARRIO LAPRIDA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (124, "1828", "VILLA BENQUEZ");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (125, "1828", "VILLA ECONOMIA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (126, "1832", "VILLA EL FARO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (127, "1828", "VILLA ELVIRA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (128, "1828", "VILLA GRAL. SAN MARTIN (BANFIELD-PDO. LOMAS DE ZAMORA)");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (129, "1836", "VILLA HENZ");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (130, "1834", "VILLA LA PAZ");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (131, "1773", "VILLA MADRID");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (132, "1834", "VILLA RATTI");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (133, "1828", "VILLA RECREO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (134, "1773", "VILLA RIACHUELO");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (135, "1832", "VILLA RITA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (136, "1834", "VILLA SASTRE");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (137, "1834", "VILLA TURDERA");
INSERT INTO `lugar` (`id`, `codigopostal`, `lugar`) VALUES (138, "1773", "VILLA URBANA");